/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cascading.avro;

@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class md5 extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = 6813541977875529663L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"md5\",\"namespace\":\"cascading.avro\",\"size\":16}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  /**
   * Creates a new md5
   */
  public md5() {
    super();
  }

  /**
   * Creates a new md5 with the given bytes.
   *
   * @param bytes The bytes to create the new md5.
   */
  public md5(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter<md5>
          WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<md5>(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader<md5>
          READER$ = new org.apache.avro.specific.SpecificDatumReader<md5>(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
