/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cascading.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class test4 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8818813708461575185L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"test4\",\"namespace\":\"cascading.avro\",\"fields\":[{\"name\":\"aListOfListOfInt\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"int\"}}},{\"name\":\"aListOfMapToLong\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"map\",\"values\":\"long\"}}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<test4> ENCODER =
          new BinaryMessageEncoder<test4>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<test4> DECODER =
          new BinaryMessageDecoder<test4>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<test4> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<test4> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<test4> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<test4>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this test4 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a test4 from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a test4 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static test4 fromByteBuffer(
          java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<java.util.List<java.lang.Integer>> aListOfListOfInt;
  private java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> aListOfMapToLong;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public test4() {
  }

  /**
   * All-args constructor.
   *
   * @param aListOfListOfInt The new value for aListOfListOfInt
   * @param aListOfMapToLong The new value for aListOfMapToLong
   */
  public test4(java.util.List<java.util.List<java.lang.Integer>> aListOfListOfInt, java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> aListOfMapToLong) {
    this.aListOfListOfInt = aListOfListOfInt;
    this.aListOfMapToLong = aListOfMapToLong;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return aListOfListOfInt;
      case 1:
        return aListOfMapToLong;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        aListOfListOfInt = (java.util.List<java.util.List<java.lang.Integer>>) value$;
        break;
      case 1:
        aListOfMapToLong = (java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>>) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'aListOfListOfInt' field.
   * @return The value of the 'aListOfListOfInt' field.
   */
  public java.util.List<java.util.List<java.lang.Integer>> getAListOfListOfInt() {
    return aListOfListOfInt;
  }


  /**
   * Sets the value of the 'aListOfListOfInt' field.
   * @param value the value to set.
   */
  public void setAListOfListOfInt(java.util.List<java.util.List<java.lang.Integer>> value) {
    this.aListOfListOfInt = value;
  }

  /**
   * Gets the value of the 'aListOfMapToLong' field.
   *
   * @return The value of the 'aListOfMapToLong' field.
   */
  public java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> getAListOfMapToLong() {
    return aListOfMapToLong;
  }


  /**
   * Sets the value of the 'aListOfMapToLong' field.
   *
   * @param value the value to set.
   */
  public void setAListOfMapToLong(java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> value) {
    this.aListOfMapToLong = value;
  }

  /**
   * Creates a new test4 RecordBuilder.
   * @return A new test4 RecordBuilder
   */
  public static cascading.avro.test4.Builder newBuilder() {
    return new cascading.avro.test4.Builder();
  }

  /**
   * Creates a new test4 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new test4 RecordBuilder
   */
  public static cascading.avro.test4.Builder newBuilder(cascading.avro.test4.Builder other) {
    if (other == null) {
      return new cascading.avro.test4.Builder();
    } else {
      return new cascading.avro.test4.Builder(other);
    }
  }

  /**
   * Creates a new test4 RecordBuilder by copying an existing test4 instance.
   * @param other The existing instance to copy.
   * @return A new test4 RecordBuilder
   */
  public static cascading.avro.test4.Builder newBuilder(cascading.avro.test4 other) {
    if (other == null) {
      return new cascading.avro.test4.Builder();
    } else {
      return new cascading.avro.test4.Builder(other);
    }
  }

  /**
   * RecordBuilder for test4 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<test4>
          implements org.apache.avro.data.RecordBuilder<test4> {

    private java.util.List<java.util.List<java.lang.Integer>> aListOfListOfInt;
    private java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> aListOfMapToLong;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cascading.avro.test4.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.aListOfListOfInt)) {
        this.aListOfListOfInt = data().deepCopy(fields()[0].schema(), other.aListOfListOfInt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.aListOfMapToLong)) {
        this.aListOfMapToLong = data().deepCopy(fields()[1].schema(), other.aListOfMapToLong);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing test4 instance
     * @param other The existing instance to copy.
     */
    private Builder(cascading.avro.test4 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.aListOfListOfInt)) {
        this.aListOfListOfInt = data().deepCopy(fields()[0].schema(), other.aListOfListOfInt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aListOfMapToLong)) {
        this.aListOfMapToLong = data().deepCopy(fields()[1].schema(), other.aListOfMapToLong);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'aListOfListOfInt' field.
      * @return The value.
      */
    public java.util.List<java.util.List<java.lang.Integer>> getAListOfListOfInt() {
      return aListOfListOfInt;
    }


    /**
     * Sets the value of the 'aListOfListOfInt' field.
     * @param value The value of 'aListOfListOfInt'.
      * @return This builder.
      */
    public cascading.avro.test4.Builder setAListOfListOfInt(java.util.List<java.util.List<java.lang.Integer>> value) {
      validate(fields()[0], value);
      this.aListOfListOfInt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'aListOfListOfInt' field has been set.
     * @return True if the 'aListOfListOfInt' field has been set, false otherwise.
      */
    public boolean hasAListOfListOfInt() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'aListOfListOfInt' field.
      * @return This builder.
      */
    public cascading.avro.test4.Builder clearAListOfListOfInt() {
      aListOfListOfInt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'aListOfMapToLong' field.
     *
     * @return The value.
     */
    public java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> getAListOfMapToLong() {
      return aListOfMapToLong;
    }


    /**
     * Sets the value of the 'aListOfMapToLong' field.
     *
     * @param value The value of 'aListOfMapToLong'.
     * @return This builder.
     */
    public cascading.avro.test4.Builder setAListOfMapToLong(java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> value) {
      validate(fields()[1], value);
      this.aListOfMapToLong = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'aListOfMapToLong' field has been set.
      * @return True if the 'aListOfMapToLong' field has been set, false otherwise.
     */
    public boolean hasAListOfMapToLong() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'aListOfMapToLong' field.
      * @return This builder.
      */
    public cascading.avro.test4.Builder clearAListOfMapToLong() {
      aListOfMapToLong = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public test4 build() {
      try {
        test4 record = new test4();
        record.aListOfListOfInt = fieldSetFlags()[0] ? this.aListOfListOfInt : (java.util.List<java.util.List<java.lang.Integer>>) defaultValue(fields()[0]);
        record.aListOfMapToLong = fieldSetFlags()[1] ? this.aListOfMapToLong : (java.util.List<java.util.Map<java.lang.CharSequence,java.lang.Long>>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<test4>
          WRITER$ = (org.apache.avro.io.DatumWriter<test4>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<test4>
          READER$ = (org.apache.avro.io.DatumReader<test4>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out)
          throws java.io.IOException {
    long size0 = this.aListOfListOfInt.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.List<java.lang.Integer> e0 : this.aListOfListOfInt) {
      actualSize0++;
      out.startItem();
      long size1 = e0.size();
      out.writeArrayStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.lang.Integer e1: e0) {
        actualSize1++;
        out.startItem();
        out.writeInt(e1);
      }
      out.writeArrayEnd();
      if (actualSize1 != size1)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    long size2 = this.aListOfMapToLong.size();
    out.writeArrayStart();
    out.setItemCount(size2);
    long actualSize2 = 0;
    for (java.util.Map<java.lang.CharSequence, java.lang.Long> e2 : this.aListOfMapToLong) {
      actualSize2++;
      out.startItem();
      long size3 = e2.size();
      out.writeMapStart();
      out.setItemCount(size3);
      long actualSize3 = 0;
      for (java.util.Map.Entry<java.lang.CharSequence, java.lang.Long> e3 : e2.entrySet()) {
        actualSize3++;
        out.startItem();
        out.writeString(e3.getKey());
        java.lang.Long v3 = e3.getValue();
        out.writeLong(v3);
      }
      out.writeMapEnd();
      if (actualSize3 != size3)
        throw new java.util.ConcurrentModificationException("Map-size written was " + size3 + ", but element count was " + actualSize3 + ".");
    }
    out.writeArrayEnd();
    if (actualSize2 != size2)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size2 + ", but element count was " + actualSize2 + ".");

  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in)
          throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.util.List<java.lang.Integer>> a0 = this.aListOfListOfInt;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.util.List<java.lang.Integer>>((int) size0, SCHEMA$.getField("aListOfListOfInt").schema());
        this.aListOfListOfInt = a0;
      } else a0.clear();
      SpecificData.Array<java.util.List<java.lang.Integer>> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.util.List<java.lang.Integer>>) a0 : null);
      for (; 0 < size0; size0 = in.arrayNext()) {
        for (; size0 != 0; size0--) {
          java.util.List<java.lang.Integer> e0 = (ga0 != null ? ga0.peek() : null);
          long size1 = in.readArrayStart();
          java.util.List<java.lang.Integer> a1 = e0;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.Integer>((int) size1, SCHEMA$.getField("aListOfListOfInt").schema().getElementType());
            e0 = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.Integer> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>) a1 : null);
          for (; 0 < size1; size1 = in.arrayNext()) {
            for (; size1 != 0; size1--) {
              java.lang.Integer e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readInt();
              a1.add(e1);
            }
          }
          a0.add(e0);
        }
      }

      long size2 = in.readArrayStart();
      java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> a2 = this.aListOfMapToLong;
      if (a2 == null) {
        a2 = new SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>>((int) size2, SCHEMA$.getField("aListOfMapToLong").schema());
        this.aListOfMapToLong = a2;
      } else a2.clear();
      SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>> ga2 = (a2 instanceof SpecificData.Array ? (SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>>) a2 : null);
      for (; 0 < size2; size2 = in.arrayNext()) {
        for (; size2 != 0; size2--) {
          java.util.Map<java.lang.CharSequence, java.lang.Long> e2 = (ga2 != null ? ga2.peek() : null);
          long size3 = in.readMapStart();
          java.util.Map<java.lang.CharSequence, java.lang.Long> m3 = e2; // Need fresh name due to limitation of macro system
          if (m3 == null) {
            m3 = new java.util.HashMap<java.lang.CharSequence, java.lang.Long>((int) size3);
            e2 = m3;
          } else m3.clear();
          for (; 0 < size3; size3 = in.mapNext()) {
            for (; size3 != 0; size3--) {
              java.lang.CharSequence k3 = null;
              k3 = in.readString(k3 instanceof Utf8 ? (Utf8) k3 : null);
              java.lang.Long v3 = null;
              v3 = in.readLong();
              m3.put(k3, v3);
            }
          }
          a2.add(e2);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            long size0 = in.readArrayStart();
            java.util.List<java.util.List<java.lang.Integer>> a0 = this.aListOfListOfInt;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.util.List<java.lang.Integer>>((int) size0, SCHEMA$.getField("aListOfListOfInt").schema());
              this.aListOfListOfInt = a0;
            } else a0.clear();
            SpecificData.Array<java.util.List<java.lang.Integer>> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.util.List<java.lang.Integer>>) a0 : null);
            for (; 0 < size0; size0 = in.arrayNext()) {
              for (; size0 != 0; size0--) {
                java.util.List<java.lang.Integer> e0 = (ga0 != null ? ga0.peek() : null);
                long size1 = in.readArrayStart();
                java.util.List<java.lang.Integer> a1 = e0;
                if (a1 == null) {
                  a1 = new SpecificData.Array<java.lang.Integer>((int) size1, SCHEMA$.getField("aListOfListOfInt").schema().getElementType());
                  e0 = a1;
                } else a1.clear();
                SpecificData.Array<java.lang.Integer> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>) a1 : null);
                for (; 0 < size1; size1 = in.arrayNext()) {
                  for (; size1 != 0; size1--) {
                    java.lang.Integer e1 = (ga1 != null ? ga1.peek() : null);
                    e1 = in.readInt();
                    a1.add(e1);
                  }
                }
                a0.add(e0);
              }
            }
            break;

          case 1:
            long size2 = in.readArrayStart();
            java.util.List<java.util.Map<java.lang.CharSequence, java.lang.Long>> a2 = this.aListOfMapToLong;
            if (a2 == null) {
              a2 = new SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>>((int) size2, SCHEMA$.getField("aListOfMapToLong").schema());
              this.aListOfMapToLong = a2;
            } else a2.clear();
            SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>> ga2 = (a2 instanceof SpecificData.Array ? (SpecificData.Array<java.util.Map<java.lang.CharSequence, java.lang.Long>>) a2 : null);
            for (; 0 < size2; size2 = in.arrayNext()) {
              for (; size2 != 0; size2--) {
                java.util.Map<java.lang.CharSequence, java.lang.Long> e2 = (ga2 != null ? ga2.peek() : null);
                long size3 = in.readMapStart();
                java.util.Map<java.lang.CharSequence, java.lang.Long> m3 = e2; // Need fresh name due to limitation of macro system
                if (m3 == null) {
                  m3 = new java.util.HashMap<java.lang.CharSequence, java.lang.Long>((int) size3);
                  e2 = m3;
                } else m3.clear();
                for (; 0 < size3; size3 = in.mapNext()) {
                  for (; size3 != 0; size3--) {
                    java.lang.CharSequence k3 = null;
                    k3 = in.readString(k3 instanceof Utf8 ? (Utf8) k3 : null);
                    java.lang.Long v3 = null;
                    v3 = in.readLong();
                    m3.put(k3, v3);
                  }
                }
                a2.add(e2);
              }
            }
            break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










